### PR TITLE
Fix selectors to show selected item

### LINKED ISSUE #28: Fix selector UI
The selectors do not show the already-selected values, so a user won't be able to double-check what they're viewing. Fix this.

### PR DESCRIPTION
**Pull request by corviday**
This project uses sophisticated selectors from [pcic-react-components](https://github.com/pacificclimate/pcic-react-components). Previously I'd misunderstood how the selectors worked, and as a result, when you selected an item with a dropdown, the dropdown would remain blank - it would not show which item you had selected. I was passing it the wrong thing.

All components with a selector have been modified to store the correct component in state; in the case of MapDisplay a new state variable was added to do this.

Demo [here](https://services.pacificclimate.org/dev/scip/app/).

Resolves #28

### CODE REVIEW

File: src/components/AreaDisplay/AreaDisplay.js [hunk 1]
```diff
@@ -25,17 +26,17 @@ function AreaDisplay({onChangeRegion, region}) {
...
   };
     
   return (
     <div className="AreaDisplay">
-        <p>Currently Selected Region: {region ? region.name : "none"}</p>
         <AreaSelector
             regionNames={map(regions, 'name')}
             onChange={setRegion}
-            currentRegion={region ? region.name : null}
+            currentRegion={selectedRegion ? selectedRegion : null}
```
Comment (rod-glover) [inline src/components/AreaDisplay/AreaDisplay.js:39]: A small question: What is the rationale for converting a falsy value to null explicitly? Something to do with React Select? Maybe you can just pass in the value directly?

A small observation: If the conversion _is_ important, there's a [shorthand](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing) for the conditional:  `selectedRegion ?? null`

File: src/components/DailyDataDisplay/DailyDataDisplay.js [hunk 2]
```diff
@@ -20,11 +20,11 @@ function DailyDataDisplay({region, rasterMetadata, model, emission}){
...
 
   function selectVariable(event) {
-      setVariable(event.value);
+      setVariable(event);
   }
   
   function selectClimatology(event) {
-      setClimatology(event.value);
+      setClimatology(event);
   }
```
Comment (rod-glover) [inline src/components/DailyDataDisplay/DailyDataDisplay.js:28]: I'm guessing that these functions preserve the `select*` naming you use, which is a nice touch. But they just rename the function, so you could just do `const selectX = setX` or even just use the `select*` name as the output of the `useState`.

File: src/components/DailyDataDisplay/DailyDataDisplay.js [hunk 3]
```diff
@@ -60,7 +60,7 @@ function DailyDataDisplay({region, rasterMetadata, model, emission}){
         {rasterMetadata ? 
           <VariableSelector 
             metadata={rasterMetadata}
-            value={variable ? variable.representative : null}
+            value={variable ? variable : null}
```
Comment (rod-glover) [inline src/components/DailyDataDisplay/DailyDataDisplay.js:63]: Ditto re. null conversion

File: src/components/DailyDataDisplay/DailyDataDisplay.js [hunk 4]
```diff
@@ -70,7 +70,7 @@ function DailyDataDisplay({region, rasterMetadata, model, emission}){
         {rasterMetadata ? 
           <ClimatologySelector 
             metadata={rasterMetadata}
-            value={climatology ? climatology.representative : null}
+            value={climatology ? climatology : null}
```
Comment (rod-glover) [inline src/components/DailyDataDisplay/DailyDataDisplay.js:73]: Ditto re. null conversion, etc. etc.

**Review by rod-glover — APPROVED** [review]
Wow, so nice that these work!

In the demo, the graph on the right hand side doesn't change when I change watersheds. Is that right? The map does, though, and it's really snappy and cool.

It does change when I change any of the other selectors.

File: src/components/AreaDisplay/AreaDisplay.js (hunk 1 above)
Comment (corviday) [reply src/components/AreaDisplay/AreaDisplay.js:39]: I believe I read that it has to be `null` specifically to display the "Select..." message, but it's easy to confirm that empirically, and I will do so.

**Comment by corviday** [comment]
> In the demo, the graph on the right hand side doesn't change when I change watersheds. Is that right? The map does, though, and it's really snappy and cool.

I noticed this bug [yesterday](https://github.com/pacificclimate/scip-frontend/issues/38), but I'm not sure exactly when it snuck into the codebase.

File: src/components/AreaDisplay/AreaDisplay.js (hunk 1 above)
Comment (corviday) [reply src/components/AreaDisplay/AreaDisplay.js:39]: Looks like the conversion was not needed. I have simplified this, and learned something. :)
